import os
import sys
from src.mlproject.exception import CustomException
from src.mlproject.logger import logging
import pandas as pd

#pymysql, mysql-connector-python
def read_sql_data():
